### ISSUE TITLE
Have has accept only a predicate instead of predicate and value

### ISSUE THREAD

**Issue by sbelak** [clojurewerkz/ogre#57]
This would solve two issues:

1) right now it's impossible to use a unary predicate in has (for instance to check for some invariant)

2) it would remove the ambiguity of argument order. The current situation is less than ideal as the property is inserted as the second argument which breaks with clj expectations (note how > changes to < between has and every?):
```
(let [g (u/classic-tinkergraph)
       vs (q/query (v/get-all-vertices g)
                      (q/has :age > (int 30))
                      q/into-vec!)]
   (every? (partial < 30) (u/get-ages vs))))
```
On the other hand, if we automatically change the order around it might mess with the heads of people coming from Gremlin in other languages. Therefor I think it best to have the user be explicit about where to stick the property by closing over the constants themselves.

**Comment by spmallette** [comment]
I think I get what you're saying.  We need to be careful with `has` so that we don't lose query optimization.  I just noticed that we dropped use of the `Compare` enum:

https://github.com/clojurewerkz/ogre/commit/7d7bc6a4171b7fe9e0bd8dd650b2ad8fb827ec35#diff-094781c04538faedd5e9269f9627dd7dL28

Graph implementations can use that to optimize the `Traversal` - by using just random `BiPredicate` to serve that purpose vendors won't be able to optimize which means that such filters will just occur all in memory.  I probably should have caught that in the PR that brought that change.

**Comment by sbelak** [comment]
You are right, at the minimum I amend my proposition to retain the predicate and value airity. Still think has should be overloaded for unary predicates (that doesn't mess up anything as it just adds functionality that previously wasn't there).

Will also add special cases back in.

**Comment by spmallette** [comment]
:+1:

**Comment by spmallette** [comment]
done as per #61
